- name: Add user {{username}} to devhomes
  gather_facts: False 
  hosts: devhomes
  user: root
  tasks:
    - user: name="{{username}}" password="{{hash}}" group=users comment="{{fullname}}" home="/encrypted/homes/{{username}}"
    - file: src=/encrypted/homes/{{username}} dest=/home/{{username}} state=link

- name: Add user {{username}} to pvdevweb01
  gather_facts: False 
  hosts: pvdevweb01
  user: root
  tasks:
    - user: name="{{username}}" password="{{hash}}" group=users comment="{{fullname}}" home="/home/{{username}}"
    - file: src=/devhomes/{{username}} dest=/home/{{username}} state=link
