- name: Create Password Hash
  hosts: devhomes
  gather_facts: False
  vars_prompt:
  - name: password
    prompt: Text to be hashed for /etc/passwd (will not echo)
    private: yes
  tasks:
  - name: Create Salt
    shell: openssl rand -hex 4
    register: rand
  - debug: msg="Salt = {{rand.stdout}}"
  - shell: python -c 'import crypt; print crypt.crypt("{{password}}", "$6${{rand.stdout}}$")'
    register: hash
  - debug: msg="Password '******' with salt '{{rand.stdout}}' hashed as '{{hash.stdout}}'"
